import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateSystemSshKeysTable20251126000007 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS oracle.system_ssh_keys (
        id SERIAL PRIMARY KEY,
        key_name VARCHAR(100) NOT NULL UNIQUE,
        key_type VARCHAR(20) NOT NULL DEFAULT 'admin',
        public_key TEXT NOT NULL,
        private_key_encrypted TEXT NOT NULL,
        fingerprint VARCHAR(255),
        algorithm VARCHAR(20) DEFAULT 'RSA',
        key_size INTEGER DEFAULT 4096,
        is_active BOOLEAN DEFAULT true,
        description TEXT,
        created_at TIMESTAMP DEFAULT NOW(),
        updated_at TIMESTAMP DEFAULT NOW(),
        last_used_at TIMESTAMP,
        usage_count INTEGER DEFAULT 0
      );
      
      CREATE INDEX IF NOT EXISTS idx_system_ssh_keys_key_type ON oracle.system_ssh_keys(key_type);
      CREATE INDEX IF NOT EXISTS idx_system_ssh_keys_is_active ON oracle.system_ssh_keys(is_active);
      CREATE INDEX IF NOT EXISTS idx_system_ssh_keys_key_name ON oracle.system_ssh_keys(key_name);
      
      COMMENT ON TABLE oracle.system_ssh_keys IS 'Stores system-level SSH keys used for admin access to VMs and web terminal';
      COMMENT ON COLUMN oracle.system_ssh_keys.key_type IS 'Key purpose: admin (web terminal), backup, emergency';
      COMMENT ON COLUMN oracle.system_ssh_keys.private_key_encrypted IS 'AES-256 encrypted private key for system use only';
      COMMENT ON COLUMN oracle.system_ssh_keys.is_active IS 'Whether this key is currently being used for new VMs';
      COMMENT ON COLUMN oracle.system_ssh_keys.usage_count IS 'Number of VMs using this key';
      
      -- Insert default admin key (will be generated by initialization script)
      INSERT INTO oracle.system_ssh_keys (key_name, key_type, public_key, private_key_encrypted, description, is_active)
      VALUES ('default-admin-key', 'admin', 'TO_BE_GENERATED', 'TO_BE_GENERATED', 'Default admin SSH key for web terminal access', true)
      ON CONFLICT (key_name) DO NOTHING;
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DROP INDEX IF EXISTS oracle.idx_system_ssh_keys_key_name;
      DROP INDEX IF EXISTS oracle.idx_system_ssh_keys_is_active;
      DROP INDEX IF EXISTS oracle.idx_system_ssh_keys_key_type;
      DROP TABLE IF EXISTS oracle.system_ssh_keys;
    `);
  }
}
