import { MigrationInterface, QueryRunner } from 'typeorm';

export class AddWindowsPasswordToVmInstances20260121104936 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      -- Add column to store Windows initial password
      ALTER TABLE oracle.vm_instances 
        ADD COLUMN IF NOT EXISTS windows_initial_password TEXT;
      
      -- Add comment
      COMMENT ON COLUMN oracle.vm_instances.windows_initial_password 
        IS 'Initial administrator password for Windows VMs, auto-generated by OCI';
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      -- Remove the column
      ALTER TABLE oracle.vm_instances 
        DROP COLUMN IF EXISTS windows_initial_password;
    `);
  }
}
